### PR TITLE
functions for simple similarities on other nodes

### PR DESCRIPTION
**Pull request by dbross1**
Still need to connect these to the front end, and figure out where to do the calculation for the overall simple average.

### CODE REVIEW

**Review by davida26 — APPROVED** [review]

**Comment by davida26** [comment]
@alyssabedard / @nsheely - we can merge this to main but we will need the endpoints created in the backend

**Comment by nsheely** [comment]
> @alyssabedard / @nsheely - we can merge this to main but we will need the endpoints created in the backend

Cool, i'll add the endpoints and push to this real quick

**Comment by nsheely** [comment]
> > @alyssabedard / @nsheely - we can merge this to main but we will need the endpoints created in the backend
> 
> Cool, i'll add the endpoints and push to this real quick

Added the endpoints, I did a quick test to see that I could hit them but nothing thorough

**Review by nsheely — APPROVED** [review]
Good to go, certainly isn't DRY code, but it seems to work and that's what's important now

**Pull request merged**
