### PR TITLE
Average similarity scoring

### PR DESCRIPTION
**Pull request by nsheely**
Added paths for 

- average similarity by target - pass a target to get similarity score between it and every target with a similarity score connection to the queried target. When targets have multiple descriptors a simple average is used.
- weighted average similarity by target - can pass weight arguments in the url to serve as multipliers to different descriptors in the average similarity result, for example api/weighted_average_similarity/FGG/?weight_hprotein=0.2&weight_mousepheno=2.8
- global average similarity path - returns every average similarity between every target in the database. Filtered by a 'min_descriptors' argument, so you can, for example use api/global_average_similarity/6/ to get every target pair with at least 6 descriptors present - caution, extremely slow and can return a huge amount of data

### CODE REVIEW

**Comment by alyssabedard** [comment]
I'm getting the following error in Docker : 
`Failed to read from defunct connection IPv4Address(('neo4j', 7687)) (IPv4Address(('172.22.0.4', 7687)))`
` Internal Server Error: /api/global_average_similarity/6/
`
...
```
2023-05-08 14:10:09 gradvek-backend-1   |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt.py", line 739, in _set_defunct_read
2023-05-08 14:10:09 gradvek-backend-1   |     self._set_defunct(message, error=error, silent=silent)
2023-05-08 14:10:09 gradvek-backend-1   |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt.py", line 787, in _set_defunct
2023-05-08 14:10:09 gradvek-backend-1   |     raise ServiceUnavailable(message) from error
2023-05-08 14:10:09 gradvek-backend-1   | neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('neo4j', 7687)) (IPv4Address(('172.22.0.4', 7687)))
2023-05-08 14:10:09 gradvek-backend-1   | [08/May/2023 18:10:09] "GET /api/global_average_similarity/6/ HTTP/1.1" 500 181379
```

**Comment by nsheely** [comment]
> I'm getting the following error in Docker : `Failed to read from defunct connection IPv4Address(('neo4j', 7687)) (IPv4Address(('172.22.0.4', 7687)))` `Internal Server Error: /api/global_average_similarity/6/` ...
> 
> ```
> 2023-05-08 14:10:09 gradvek-backend-1   |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt.py", line 739, in _set_defunct_read
> 2023-05-08 14:10:09 gradvek-backend-1   |     self._set_defunct(message, error=error, silent=silent)
> 2023-05-08 14:10:09 gradvek-backend-1   |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt.py", line 787, in _set_defunct
> 2023-05-08 14:10:09 gradvek-backend-1   |     raise ServiceUnavailable(message) from error
> 2023-05-08 14:10:09 gradvek-backend-1   | neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('neo4j', 7687)) (IPv4Address(('172.22.0.4', 7687)))
> 2023-05-08 14:10:09 gradvek-backend-1   | [08/May/2023 18:10:09] "GET /api/global_average_similarity/6/ HTTP/1.1" 500 181379
> ```

I haven't seen this yet, but I would guess this is related to how long that route takes to return, I'll look into ways to keep the connection alive.

I updated neomodels max connection time to 3 hours ( from 1 hour ). Maybe this fixes it?

**Comment by alyssabedard** [comment]
> I haven't seen this yet, but I would guess this is related to how long that route takes to return, I'll look into ways to keep the connection alive.
> 
> I updated neomodels max connection time to 3 hours ( from 1 hour ). Maybe this fixes it?

same error with http://localhost:8000/api/global_average_similarity/4/ 🥲

**Comment by nsheely** [comment]
> > I haven't seen this yet, but I would guess this is related to how long that route takes to return, I'll look into ways to keep the connection alive.
> > I updated neomodels max connection time to 3 hours ( from 1 hour ). Maybe this fixes it?
> 
> same error with http://localhost:8000/api/global_average_similarity/4/ 🥲

Yeah, as that number goes down the data being transferred and post-processed will get bigger, making it take longer

**Comment by nsheely** [comment]
> > > I haven't seen this yet, but I would guess this is related to how long that route takes to return, I'll look into ways to keep the connection alive.
> > > I updated neomodels max connection time to 3 hours ( from 1 hour ). Maybe this fixes it?
> > 
> > 
> > same error with http://localhost:8000/api/global_average_similarity/4/ 🥲
> 
> Yeah, as that number goes down the data being transferred and post-processed will get bigger, making it take longer

Added mem_limits to containers via docker-compose. Global average similarity route now checks memory limits on host machine and just returns an empty response when less than 8GB is available. It may be possible to mitigate this with lower memory usage by using a different base image, but this seems to work for now.

**Review by alyssabedard — APPROVED** [review]
Looks good.
🤞🏼

**Review by davida26 — APPROVED** [review]
looks good to me

**Pull request merged**
